<?php

/**
 * @file
 * Bootstrap Layout Builder module.
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function bootstrap_layout_builder_theme() {
  return [
    'row_columns' => [
      'template' => 'row-columns',
      'render element' => 'content',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bootstrap_layout_builder_preprocess_row_columns(&$variables) {
  // Create an attributes variable for each region.
  foreach (Element::children($variables['content']) as $name) {
    if (!isset($variables['content'][$name]['#attributes'])) {
      $variables['content'][$name]['#attributes'] = [];
    }
    $variables['region_attributes'][$name] = new Attribute($variables['content'][$name]['#attributes']);
  }
}
